package com.techthinkers.spro.commons.util.exception;

public enum ErrorCode {
    
	GEN_EXCEPTION(500),
	HTTP_METHOD_NOT_SUPPORTED_EXCEPTION(405),
	HTTP_MEDIA_TYPE_NOT_SUPPORTED_EXCEPTION(415),
	HTTP_MEDIA_TYPE_NOT_ACCEPTABLE_EXCEPTION(406),
	MISSING_PATH_VARIABLE_EXCEPTION(405),
	MISSING_SERVLET_REQUEST_PARAMETER_EXCEPTION(405),
	MISSING_SERVLET_REQUEST_PART_EXCEPTION(405),
	SERVLET_REQUEST_BINDING_EXCEPTION(405),
	METHOD_ARGUMENT_NOT_VALID_EXCEPTION(405),
	HANDLER_METHOD_VALIDATION_EXCEPTION(500),
	NO_HANDLER_FOUND_EXCEPTION(404),
	NO_RESOURCE_FOUND_EXCEPTION(404),
	ASYNC_REQUEST_TIMEOUT_EXCEPTION(503),
	ERROR_RESPONSE_EXCEPTION(500),
	MAX_UPLOAD_SIZE_EXCEEDED_EXCEPTION(413),
	CONVERSION_NOT_SUPPORTED_EXCEPTION(500),
	TYPE_MISMATCH_EXCEPTION(405),
	HTTP_MESSAGE_NOT_READABLE_EXCEPTION(500),
	HTTP_MESSAGE_NOT_WRITABLE_EXCEPTION(500),
	BIND_EXCEPTION(405),
	METHOD_VALIDATION_EXCEPTION(405);
	
    private int responseStatus;
    
    ErrorCode(int responseStatus){
        this.responseStatus = responseStatus;
    }
 
    public int getResponseStatus() {
        return responseStatus;
    }       
}